---
services: docker

env:
#  - distro: centos7
#  - distro: centos6
#  - distro: fedora27
#  - distro: ubuntu1604
#  - distro: ubuntu1404
#  - distro: ubuntu1204

  - distro: debian9
  - distro: debian8
  - distro: ubuntu1804
  - distro: ubuntu1604

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  - export DOCKER="docker exec --tty ${container_id} env TERM=xterm"

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/tschifftner/4078cf2a8429d967d5e100649ff2caa9/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Make sure mariadb service is running
  - ${DOCKER} systemctl --no-pager status ntp | grep "running"

  # Check synchronization was successful
  - ${DOCKER} ntpstat | grep 'synchronised to NTP server'

  # Check timezone
  - ${DOCKER} cat /etc/timezone | grep 'Europe/Berlin'
  - ${DOCKER} readlink /etc/localtime | grep 'Europe/Berlin'


after_failure:
  - ${DOCKER} systemctl --no-pager status ntp
  - ${DOCKER} ntpstat
  - cat /etc/timezone
  - readlink /etc/localtime


notifications:
  slack: ambimax:2MlPTX9bY9aPxCPhJGxHKIT6
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
