---
- name: Install ntp apt packages
  apt:
    pkg: '{{ item }}'
    state: present
  with_items: '{{ datetime_apt_packages }}'

- name: Configure ntp
  template:
    src: ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart ntp

- name: Ensure ntp always runs
  service:
    name: ntp
    state: started
    enabled: yes

- name: Force time sync once (even when more than 1000 seconds difference)
  command: ntpd -g -q
  ignore_errors: true
  changed_when: false

- name: Write to hardware clock
  command: hwclock --systohc
  when: datetime_sync_hardware_clock
  ignore_errors: true
  changed_when: false
